### ISSUE TITLE
Eureka not working with java10 or java8.

### ISSUE THREAD

**Issue by alonsoir** [chuchip/springEureka#1]
Good afternoon, I've been messing with your project and I finally managed to run eureka with java11, because it didn't start with java10 or java8. I have also updated to the latest version of spring-boot. If you don't mind, I share the pom.xml for the eureka server project.

Sorry, i did not create any pull request.

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.3.RELEASE</version>
		<relativePath/> 
	</parent>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>11</java.version>
		<spring-cloud.version>Greenwich.RELEASE</spring-cloud.version>
	</properties>

New dependency

		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-runtime</artifactId>
		</dependency>

**Comment by chuchip** [comment]
Did  you can't run it with Java 8.  It work for me with Java 8 ( JRE
1.8.0_171  Oracle) . I will try to run with 8  and 11 and I'll  update the
project if they work.

Thanks  a lot for you feedback.

Regards,

Jesus
